# -*- coding: utf-8 -*-
"""Dynamic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDRTsn3Y-tqIWTcd4WAu-KWf0oipIiUR
"""


import pandas as pd
from rapidfuzz import process, fuzz

df = pd.read_excel(r"C:\Users\Hp\Downloads\Diagnoses.xlsx")

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9 ]', '', text)  
    text = re.sub(r'\s+', ' ', text)       
    return text.strip()

def get_icd10(diagnosis, df, threshold=70):
    diagnosis = clean_text(diagnosis)
    choices = df['Source'].apply(clean_text).tolist()
    match = process.extractOne(diagnosis, choices, scorer=fuzz.token_sort_ratio)

    if match and match[1] >= threshold:

        icd_info = df.iloc[match[2]][['ICD10 Code', 'MappingFieldValue']]
        return icd_info, match[1]
    else:
        return None, 0

free_text = "Breast Cancer"
icd_info, confidence = get_icd10(free_text, df)

if icd_info is not None:
    print(f"Input: {free_text} → ICD-10: {icd_info['ICD10 Code']} -> Mapping Field Value: {icd_info['MappingFieldValue']}")
else:
    print(f"No match found for {free_text}")


import streamlit as st
st.title("ICD-10 Matcher")

free_text = st.text_input("Enter Diagnosis:")

st.markdown("""
<style>
.stApp {
    background-color: black
;
}
</style>
""", unsafe_allow_html=True)

if free_text:
    icd_info, confidence = get_icd10(free_text, df)

    if icd_info is not None:
        st.success(f"Input: {free_text}")
        st.write(f"**ICD-10 Code:** {icd_info['ICD10 Code']}")
        st.write(f"**Mapping Field Value:** {icd_info['MappingFieldValue']}")
        st.write(f"**Confidence Score:** {confidence}")
    else:
        st.error(f"No match found for '{free_text}'")